export const products = [
  {
    id: "0bd85b",
    name: "هندزفری بلوتوث شیائومی مدل Redmi Buds Essential",
    categories: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "665000",
    priceOff: "623000",
    brand: "xi",
    features: [
      { title: "برند", content: "شیائومی" },
      { title: "مدل", content: "Redmi Buds Essential" },
      { title: " تایپ", content: "Tws" },
    ],
    sells: "346",
    date: "2",
    rate: "4.5",
    reviews: "102",
  },
  {
    id: "a602d0",
    name: "هدفون شیائومی مدل Headphones Piston Basic",
    categories: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "350000",
    priceOff: "300000",
    brand: "xi",
    features: [
      { title: "برند", content: "شیائومی" },
      { title: "مدل", content: "IN-EAR BASIC" },
      { title: "طول کابل", content: "1.25 متر" },
      { title: "وزن", content: "14 گرم" },
    ],
    sells: "71",
    date: "1",
    rate: "5",
    reviews: "20",
  },
  {
    id: "3945ac",
    name: "هندزفری بلوتوث شیائومی مدل Mibro Earbuds 2",
    categories: ["Wireless Headphones", "Headphones"],
    model: "Mibro Earbuds2 XPEJ004 TWS Earbuds",
    color: "black",
    priceOn: "675000",
    priceOff: "620000",
    brand: "xi",
    features: [
      { title: "برند", content: "mibro" },
      { title: "مدل", content: "Earbuds 2" },
      { title: "وزن", content: "3.4 گرم کیس شارژ : 26.7 گرم" },
    ],
    sells: "500",
    date: "12",
    rate: "4",
    reviews: "18",
  },
  {
    id: "aafbab",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T1C",
    model: "QCY T1C TWS Bluetooth Earphones Wireless Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "395000",
    priceOff: "415000",
    brand: "xi",
    features: [
      {
        content: "کیو سی وای / شیائومی",
        title: "برند",
      },
      {
        content: "T1C",
        title: "مدل",
      },
      {
        content: "In-Ear",
        title: "وع هدفون",
      },
      {
        content: "18×20×30 میلی‌متر",
        title: "ابعاد",
      },
    ],
    sells: "25000",
    date: "13",
    rate: "5",
    reviews: "1348",
  },
  {
    id: "51a3e6.png",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T16",
    model: "QCY T16 True Wireless Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "white",
    priceOn: "590000",
    priceOff: "610000",
    brand: "xi",
    features: [
      {
        content: "شیائومی",
        title: "برند",
      },
      {
        content: "QCY T16",
        title: "مدل",
      },
      {
        content: "In-Ear",
        title: " نوع هدفون",
      },
      {
        content: "10 × 10 × 10 سانتی متر",
        title: "ابعاد",
      },
    ],
    sells: "125",
    date: "15",
    rate: "4",
    reviews: "45",
  },
  {
    id: "c0fa97",
    name: "هدفون شیائومی مدل ۱More Design Piston Fit",
    model: "1MORE PISTON IN-EAR HEADPHONES E1009",
    categoreis: ["Headphones"],
    color: "any",
    priceOn: "280000",
    priceOff: "",
    brand: "xi",
    features: [
      {
        content: "شیائومی_۱More",
        title: "برند",
      },
      {
        content: "Piston fit E1009",
        title: " مدل",
      },
      {
        content: "با سیم",
        title: " نوع اتصال",
      },
    ],
    sells: "110",
    date: "5",
    rate: "5",
    reviews: "55",
  },
  {
    id: "3ad265",
    name: "هندزفری وان مور مدل 1More Triple Driver In-Ear E1001",
    model: "1MORE Triple Driver In-Ear Earphones Hi-Res Headphones E1001",
    categoreis: ["Headphones"],
    color: "gold",
    priceOn: "1500000",
    priceOff: "",
    brand: "samsung",
    features: [
      {
        content: "1MORE",
        title: "برند",
      },
      {
        content: "E1001",
        title: "مدل",
      },
      {
        content: "19گرم",
        title: "وزن",
      },
    ],
    sells: "80",
    date: "1",
    rate: "4.5",
    reviews: "35",
  },
  {
    id: "99627e",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T13",
    model: "QCY T13 True Wireless Bluetooth Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "white",
    priceOn: "550000",
    priceOff: "520000",
    brand: "samsung",
    features: [
      {
        content: "شیائومی/ QCY",
        title: " برند",
      },
      {
        content: " T13",
        title: "مدل",
      },
      {
        content: "5.5 × 5.3 × 2.7 سانتی متر",
        title: " ابعاد",
      },
    ],
    sells: "88",
    date: "52",
    rate: "4.5",
    reviews: "44",
  },
  {
    id: "4e5f09",
    name: "هندزفری بلوتوث وان مور مدل 1MORE Piston Buds",
    model: "1MORE Piston Buds ECS3001T",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "790000",
    priceOff: "",
    brand: "xi",
    features: [
      {
        content: "شیائومی، 1MORE",
        title: " برند",
      },
      {
        content: "Piston Buds",
        title: "مدل",
      },
      {
        content: " 25.7 * 36.8 * 70.6 میلی‌ متر",
        title: "ابعاد",
      },
      {
        content: "43.3 گرم",
        title: " وزن",
      },
    ],
    sells: "180",
    date: "7",
    rate: "3",
    reviews: "90",
  },
  {
    id: "b2835d",
    name: "هندزفری بلوتوث اپل مدل Earphone 2 Basic",
    model: "Xiaomi Mi True Wireless Earphone 2 Basic",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "white",
    priceOn: "569000",
    priceOff: "500000",
    brand: "apple",
    features: [
      {
        content: "اپل",
        title: " برند",
      },
      {
        content: "2 Basic",
        title: "مدل",
      },
      {
        content: "۵۰ * 35 * 20 میلی‌ متر",
        title: " نوع هدفون",
      },
    ],
    sells: "120",
    date: "12",
    rate: "4.5",
    reviews: "60",
  },
  {
    id: "609214",
    name: "هندزفری بلوتوث دور گردنی اومتینگ وان مور مدل 1More EO008 Omthing AirFree Lace",
    model: "1More EO008 Omthing AirFree Lace Wireless Headphones",
    categoreis: ["Headphones"],
    color: "black",
    priceOn: "570000",
    priceOff: "",
    brand: "samsung",
    features: [
      {
        content: "وان مور",
        title: "برند",
      },
      {
        content: "EO008 Omthing AirFree Lace",
        title: "مدل",
      },
      {
        content: "28.4 گرم",
        title: "وزن",
      },
    ],
    sells: "98",
    date: "1",
    rate: "5",
    reviews: "51",
  },
  {
    id: "1b61a2.png",
    name: "هندزفری بلوتوثی شیائومی Redmi Buds 4 Pro",
    model: "Xiaomi Buds 4 Pro Bluetooth Earphones",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "6500000",
    priceOff: "6350000",
    brand: "apple",
    features: [
      {
        content: " Redmi",
        title: "برند",
      },
      {
        content: "Redmi Buds 4 Pro",
        title: "مدل",
      },
    ],
    sells: "0",
    date: "1",
    rate: "0",
    reviews: "0",
  },
  {
    id: "60c40b.png",
    name: "هندزفری بلوتوث هایلو مدل Haylou GT1 Pro",
    model: "Haylou GT1 Pro Bluetooth Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "540000",
    priceOff: "",
    brand: "sony",
    features: [
      {
        content: "هایلو",
        title: " برند",
      },
      {
        content: "GT1 Pro",
        title: "مدل",
      },
      {
        content: "۶٫۲ × ۴ × ۲٫۷ سانتی متر",
        title: " ابعاد",
      },
    ],
    sells: "500",
    date: "5",
    rate: "4.5",
    reviews: "214",
  },
  {
    id: "289374.png",
    name: "هندزفری بلوتوث دورگردنی شیائومی مدل LYXQEJ01JY",
    model: "Xiaomi LYXQEJ01JY Bluetooth Necklace Headphones",
    categoreis: ["Headphones"],
    color: "white",
    priceOn: "1000000",
    priceOff: "960000",
    brand: "xi",
    features: [
      {
        content: " شیائومی",
        title: "برند",
      },
      {
        content: "LYXQEJ01JY",
        title: " مدل",
      },
      {
        content: "ABS",
        title: " جنس:",
      },
    ],
    sells: "670",
    date: "14",
    rate: "3",
    reviews: "373",
  },
  {
    id: "1865c3",
    name: "هدفون بی سیم ناتینگ مدل Nothing Ear 1",
    model: "Nothing Ear 1 Wireless Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "white",
    priceOn: "2270000",
    priceOff: "",
    brand: "sony",
    features: [
      {
        content: "سونی",
        title: "برند",
      },
      {
        content: "Nothing Ear 1",
        title: "مدل",
      },
      {
        content: "4.7 گرم",
        title: " وزن هر ایرباد",
      },
    ],
    sells: "60",
    date: "21",
    rate: "5",
    reviews: "30",
  },
  {
    id: "909315",
    name: "هندزفری بلوتوث بلک شارک Black Shark joybuds",
    model: "Black Shark Fengming True Wireless Bluetooth Headset",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "white",
    priceOn: "2190000",
    priceOff: "",
    brand: "apple",
    features: [
      {
        content: "بلک شارک",
        title: "برند",
      },
      {
        content: "Black Shark joybuds",
        title: "مدل",
      },
      {
        content: "پلاستیک ABS",
        title: "جنس",
      },
    ],
    sells: "110",
    date: "14",
    rate: "4.5",
    reviews: "55",
  },
  {
    id: "472248.png",
    name: "هندزفری بلوتوث هایلو مدل Haylou GT7 NEO",
    model: "HAYLOU GT7 Neo Wireless Earphone Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "680000",
    priceOff: "",
    brand: "apple",
    features: [
      {
        content: " بلوتوث نسخه 5.2",
        title: "رابط",
      },
      {
        content: "24.7 × 50.6 × 50.6 میلی‌متر",
        title: "ابعاد",
      },
      {
        content: "هر هدفون 3.9 گرم",
        title: "وزن",
      },
    ],
    sells: "40",
    date: "19",
    rate: "4.5",
    reviews: "17",
  },
  {
    id: "2cdd8f.jpeg",
    name: "هندزفری بلک شارک Black Shark Lucifer T2",
    model: "black shark lucifer t2Wireless Earbuds T2",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "197000",
    priceOff: "",
    brand: "xi",
    features: [
      {
        content: "شیائومی- Black Shark",
        title: " برند",
      },
      {
        content: "Lucifer T2",
        title: "مدل",
      },
      {
        content: "پشت بسته (Closed-Back)",
        title: "نوع آکوستیک",
      },
    ],
    sells: "1530000",
    date: "23",
    rate: "5",
    reviews: "220",
  },
  {
    id: "1bb820.jpg",
    name: "هندزفری بلوتوث هایلو مدل Haylou X1 PRO",
    model: "Haylou X1 Pro True Wireless Earbuds",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: "1340000",
    priceOff: "",
    brand: "apple",
    features: [
      {
        content: "اپل",
        title: " برند",
      },
      {
        content: "Haylou X1 PRO",
        title: "مدل",
      },
      {
        content: "35 گرم",
        title: "وزن",
      },
    ],
    sells: "300",
    date: "12",
    rate: "4",
    reviews: "150",
  },
  {
    id: "068db9",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T12S",
    model: "هندزفری بلوتوث کیو سی وای مدل QCY T12S",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "colory",
    priceOn: "550000",
    priceOff: "",
    brand: "sony",
    features: [
      {
        content: "QCY",
        title: "برند",
      },
      {
        content: "in2027",
        title: " نام فنی مدل",
      },
      {
        content: "پلاستیک",
        title: " جنس بدنه",
      },
      {
        content: "سرمه ای",
        title: " رنگ",
      },
    ],
    sells: "66",
    date: "27",
    rate: "5",
    reviews: "36",
  },
  {
    id: "a8593f",
    name: "هندزفری بلوتوث وان پلاس مدل E501A",
    model: "OnePlus Buds Bluetooth Handsfree E501A",
    categoreis: ["Wireless Headphones", "Headphones"],
    color: "colory",
    priceOn: "2050000",
    priceOff: "2000000",
    brand: "xi",
    features: [
      {
        content: "شیائومی",
        title: "برند",
      },
      {
        content: "OnePlus E501A",
        title: "مدل",
      },
      {
        content: "18.81*16.13*37.89 میلی متر",
        title: " ابعاد کیس شارژ",
      },
    ],
    sells: "240",
    date: "19",
    rate: "4.5",
    reviews: "120",
  },
];
