export const AllProducts = [
  {
    id: "0bd85b.jpg",
    name: "هندزفری بلوتوث شیائومی مدل Redmi Buds Essential",
    categories: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: 665000,
    priceOff: 623000,
    brand: "xi",
    features: [
      { title: "برند", content: "شیائومی" },
      { title: "مدل", content: "Redmi Buds Essential" },
      { title: " تایپ", content: "Tws" },
    ],
    sells: 346,
    date: 2,
    rate: 4.5,
    reviews: 102,
    exist: false,
    amount: 1,
  },
  {
    id: "a602d0.jpg",
    name: "هدفون شیائومی مدل Headphones Piston Basic",
    categories: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: 350000,
    priceOff: 300000,
    brand: "xi",
    features: [
      { title: "برند", content: "شیائومی" },
      { title: "مدل", content: "IN-EAR BASIC" },
      { title: "طول کابل", content: "1.25 متر" },
      { title: "وزن", content: "14 گرم" },
    ],
    sells: 71,
    date: 1,
    rate: 5,
    reviews: 20,
    exist: true,
    amount: 1,
  },
  {
    id: "3945ac.jpg",
    name: "هندزفری بلوتوث شیائومی مدل Mibro Earbuds 2",
    categories: ["Wireless Headphones", "Headphones"],
    model: "Mibro Earbuds2 XPEJ004 TWS Earbuds",
    color: "black",
    priceOn: 675000,
    priceOff: 620000,
    brand: "xi",
    features: [
      { title: "برند", content: "mibro" },
      { title: "مدل", content: "Earbuds 2" },
      { title: "وزن", content: "3.4 گرم کیس شارژ : 26.7 گرم" },
    ],
    sells: 500,
    date: 12,
    rate: 4,
    reviews: 18,
    exist: false,
    amount: 1,
  },
  {
    id: "aafbab.jpg",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T1C",
    model: "QCY T1C TWS Bluetooth Earphones Wireless Earbuds",
    categories: ["Wireless Headphones", "Headphones"],
    color: "black",
    priceOn: 395000,
    priceOff: 415000,
    brand: "xi",
    features: [
      {
        content: "کیو سی وای / شیائومی",
        title: "برند",
      },
      {
        content: "T1C",
        title: "مدل",
      },
      {
        content: "In-Ear",
        title: "وع هدفون",
      },
      {
        content: "18×20×30 میلی‌متر",
        title: "ابعاد",
      },
    ],
    sells: 25000,
    date: 13,
    rate: 5,
    reviews: 1348,
    exist: true,
    amount: 1,
  },
  {
    id: "51a3e6.png",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T16",
    model: "QCY T16 True Wireless Earbuds",
    categories: ["Wireless Headphones", "Headphones"],
    color: "white",
    priceOn: 590000,
    priceOff: 610000,
    brand: "xi",
    features: [
      {
        content: "شیائومی",
        title: "برند",
      },
      {
        content: "QCY T16",
        title: "مدل",
      },
      {
        content: "In-Ear",
        title: " نوع هدفون",
      },
      {
        content: "10 × 10 × 10 سانتی متر",
        title: "ابعاد",
      },
    ],
    sells: 125,
    date: 15,
    rate: 4,
    reviews: 45,
    exist: true,
    amount: 1,
  },
  {
    id: "c0fa97.jpg",
    name: "هدفون شیائومی مدل ۱More Design Piston Fit",
    model: "1MORE PISTON IN-EAR HEADPHONES E1009",
    categories: ["Headphones"],
    color: "colory",
    priceOn: 280000,
    priceOff: 0,
    brand: "xi",
    features: [
      {
        content: "شیائومی_۱More",
        title: "برند",
      },
      {
        content: "Piston fit E1009",
        title: " مدل",
      },
      {
        content: "با سیم",
        title: " نوع اتصال",
      },
    ],
    sells: 110,
    date: 5,
    rate: 5,
    reviews: 55,
    exist: true,
    amount: 1,
  },
  {
    id: "3ad265.jpg",
    name: "هندزفری وان مور مدل 1More Triple Driver In-Ear E1001",
    model: "1MORE Triple Driver In-Ear Earphones Hi-Res Headphones E1001",
    categories: ["Headphones"],
    color: "colory",
    priceOn: 1500000,
    priceOff: 0,
    brand: "samsung",
    features: [
      {
        content: "1MORE",
        title: "برند",
      },
      {
        content: "E1001",
        title: "مدل",
      },
      {
        content: "19گرم",
        title: "وزن",
      },
    ],
    sells: 80,
    date: 1,
    rate: 4.5,
    reviews: 35,
    exist: false,
    amount: 1,
  },
  {
    id: "99627e.png",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T13",
    model: "QCY T13 True Wireless Bluetooth Earbuds",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "white",
    priceOn: 550000,
    priceOff: 520000,
    brand: "samsung",
    features: [
      {
        content: "شیائومی/ QCY",
        title: " برند",
      },
      {
        content: " T13",
        title: "مدل",
      },
      {
        content: "5.5 × 5.3 × 2.7 سانتی متر",
        title: " ابعاد",
      },
    ],
    sells: 88,
    date: 52,
    rate: 4.5,
    reviews: 44,
    exist: true,
    amount: 1,
  },
  {
    id: "4e5f09.jpg",
    name: "هندزفری بلوتوث وان مور مدل 1MORE Piston Buds",
    model: "1MORE Piston Buds ECS3001T",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "black",
    priceOn: 790000,
    priceOff: 0,
    brand: "xi",
    features: [
      {
        content: "شیائومی، 1MORE",
        title: " برند",
      },
      {
        content: "Piston Buds",
        title: "مدل",
      },
      {
        content: " 25.7 * 36.8 * 70.6 میلی‌ متر",
        title: "ابعاد",
      },
      {
        content: "43.3 گرم",
        title: " وزن",
      },
    ],
    sells: 180,
    date: 7,
    rate: 3,
    reviews: 90,
    exist: false,
    amount: 1,
  },
  {
    id: "b2835d.jpg",
    name: "هندزفری بلوتوث اپل مدل Earphone 2 Basic",
    model: "Xiaomi Mi True Wireless Earphone 2 Basic",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "white",
    priceOn: 569000,
    priceOff: 500000,
    brand: "apple",
    features: [
      {
        content: "اپل",
        title: " برند",
      },
      {
        content: "2 Basic",
        title: "مدل",
      },
      {
        content: "۵۰ * 35 * 20 میلی‌ متر",
        title: " نوع هدفون",
      },
    ],
    sells: 120,
    date: 12,
    rate: 4.5,
    reviews: 60,
    exist: true,
    amount: 1,
  },
  {
    id: "609214.jpg",
    name: "هندزفری بلوتوث دور گردنی اومتینگ وان مور مدل 1More EO008 Omthing AirFree Lace",
    model: "1More EO008 Omthing AirFree Lace Wireless Headphones",
    categories: ["Headphones", "Appliance"],
    color: "black",
    priceOn: 570000,
    priceOff: 0,
    brand: "samsung",
    features: [
      {
        content: "وان مور",
        title: "برند",
      },
      {
        content: "EO008 Omthing AirFree Lace",
        title: "مدل",
      },
      {
        content: "28.4 گرم",
        title: "وزن",
      },
    ],
    sells: 98,
    date: 1,
    rate: 5,
    reviews: 51,
    exist: true,
    amount: 1,
  },
  {
    id: "1b61a2.png",
    name: "هندزفری بلوتوثی شیائومی Redmi Buds 4 Pro",
    model: "Xiaomi Buds 4 Pro Bluetooth Earphones",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "black",
    priceOn: 6500000,
    priceOff: 6350000,
    brand: "apple",
    features: [
      {
        content: " Redmi",
        title: "برند",
      },
      {
        content: "Redmi Buds 4 Pro",
        title: "مدل",
      },
    ],
    sells: 0,
    date: 1,
    rate: 0,
    reviews: 0,
    exist: false,
    amount: 1,
  },
  {
    id: "60c40b.png",
    name: "هندزفری بلوتوث هایلو مدل Haylou GT1 Pro",
    model: "Haylou GT1 Pro Bluetooth Earbuds",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "black",
    priceOn: 540000,
    priceOff: 0,
    brand: "sony",
    features: [
      {
        content: "هایلو",
        title: " برند",
      },
      {
        content: "GT1 Pro",
        title: "مدل",
      },
      {
        content: "۶٫۲ × ۴ × ۲٫۷ سانتی متر",
        title: " ابعاد",
      },
    ],
    sells: 500,
    date: 5,
    rate: 4.5,
    reviews: 214,
    exist: true,
    amount: 1,
  },
  {
    id: "289374.png",
    name: "هندزفری بلوتوث دورگردنی شیائومی مدل LYXQEJ01JY",
    model: "Xiaomi LYXQEJ01JY Bluetooth Necklace Headphones",
    categories: ["Headphones", "Appliance"],
    color: "white",
    priceOn: 1000000,
    priceOff: 960000,
    brand: "xi",
    features: [
      {
        content: " شیائومی",
        title: "برند",
      },
      {
        content: "LYXQEJ01JY",
        title: " مدل",
      },
      {
        content: "ABS",
        title: " جنس:",
      },
    ],
    sells: 670,
    date: 14,
    rate: 3,
    reviews: 373,
    exist: false,
    amount: 1,
  },
  {
    id: "1865c3.jpg",
    name: "هدفون بی سیم ناتینگ مدل Nothing Ear 1",
    model: "Nothing Ear 1 Wireless Earbuds",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "white",
    priceOn: 2270000,
    priceOff: 0,
    brand: "sony",
    features: [
      {
        content: "سونی",
        title: "برند",
      },
      {
        content: "Nothing Ear 1",
        title: "مدل",
      },
      {
        content: "4.7 گرم",
        title: " وزن هر ایرباد",
      },
    ],
    sells: 60,
    date: 21,
    rate: 5,
    reviews: 30,
    exist: false,
    amount: 1,
  },
  {
    id: "909315.jpg",
    name: "هندزفری بلوتوث بلک شارک Black Shark joybuds",
    model: "Black Shark Fengming True Wireless Bluetooth Headset",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "white",
    priceOn: 2190000,
    priceOff: 0,
    brand: "apple",
    features: [
      {
        content: "بلک شارک",
        title: "برند",
      },
      {
        content: "Black Shark joybuds",
        title: "مدل",
      },
      {
        content: "پلاستیک ABS",
        title: "جنس",
      },
    ],
    sells: 110,
    date: 14,
    rate: 4.5,
    reviews: 55,
    exist: true,
    amount: 1,
  },
  {
    id: "472248.png",
    name: "هندزفری بلوتوث هایلو مدل Haylou GT7 NEO",
    model: "HAYLOU GT7 Neo Wireless Earphone Earbuds",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "black",
    priceOn: 680000,
    priceOff: 0,
    brand: "apple",
    features: [
      {
        content: " بلوتوث نسخه 5.2",
        title: "رابط",
      },
      {
        content: "24.7 × 50.6 × 50.6 میلی‌متر",
        title: "ابعاد",
      },
      {
        content: "هر هدفون 3.9 گرم",
        title: "وزن",
      },
    ],
    sells: 40,
    date: 19,
    rate: 4.5,
    reviews: 17,
    exist: false,
    amount: 1,
  },
  {
    id: "2cdd8f.jpeg",
    name: "هندزفری بلک شارک Black Shark Lucifer T2",
    model: "black shark lucifer t2Wireless Earbuds T2",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "black",
    priceOn: 197000,
    priceOff: 0,
    brand: "xi",
    features: [
      {
        content: "شیائومی- Black Shark",
        title: " برند",
      },
      {
        content: "Lucifer T2",
        title: "مدل",
      },
      {
        content: "پشت بسته (Closed-Back)",
        title: "نوع آکوستیک",
      },
    ],
    sells: 1530000,
    date: 23,
    rate: 5,
    reviews: 220,
    exist: true,
    amount: 1,
  },
  {
    id: "1bb820.jpg",
    name: "هندزفری بلوتوث هایلو مدل Haylou X1 PRO",
    model: "Haylou X1 Pro True Wireless Earbuds",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "black",
    priceOn: 1340000,
    priceOff: 0,
    brand: "apple",
    features: [
      {
        content: "اپل",
        title: " برند",
      },
      {
        content: "Haylou X1 PRO",
        title: "مدل",
      },
      {
        content: "35 گرم",
        title: "وزن",
      },
    ],
    sells: 300,
    date: 12,
    rate: 4,
    reviews: 150,
    exist: true,
    amount: 1,
  },
  {
    id: "068db9.jpg",
    name: "هندزفری بلوتوث کیو سی وای مدل QCY T12S",
    model: "هندزفری بلوتوث کیو سی وای مدل QCY T12S",
    categories: ["Wireless Headphones", "Headphones", "Appliance"],
    color: "colory",
    priceOn: 550000,
    priceOff: 0,
    brand: "sony",
    features: [
      {
        content: "QCY",
        title: "برند",
      },
      {
        content: "in2027",
        title: " نام فنی مدل",
      },
      {
        content: "پلاستیک",
        title: " جنس بدنه",
      },
      {
        content: "سرمه ای",
        title: " رنگ",
      },
    ],
    sells: 66,
    date: 27,
    rate: 5,
    reviews: 36,
    exist: true,
    amount: 1,
  },
  {
    id: "a8593f.jpg",
    name: "هندزفری بلوتوث وان پلاس مدل E501A",
    model: "OnePlus Buds Bluetooth Handsfree E501A",
    categories: ["Wireless Headphones", "Headphones"],
    color: "colory",
    priceOn: 2050000,
    priceOff: 2000000,
    brand: "xi",
    features: [
      {
        content: "شیائومی",
        title: "برند",
      },
      {
        content: "OnePlus E501A",
        title: "مدل",
      },
      {
        content: "18.81*16.13*37.89 میلی متر",
        title: " ابعاد کیس شارژ",
      },
    ],
    sells: 240,
    date: 19,
    rate: 4.5,
    reviews: 120,
    exist: true,
    amount: 1,
  },
  {
    id: "f3eb38.jpeg",
    name: "گوشی موبایل شیائومی Redmi 9C ظرفیت 32/2 گیگابایت",
    engName: "",
    model: "redmi 9c xiaomi",
    categories: ["Mobile"],
    priceOn: 3_900_000,
    priceOff: null,
    brand: "xi",
    features: [
      {
        content: " دو سیم کارت",
        title: " تعداد سیم کارت",
      },
      {
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
        title: " توضیحات سیم کارت",
      },
      {
        content: "2020",
        title: " سال تولید",
      },
      {
        content: "2 GB",
        title: "رم",
      },
      {
        content: "13MP",
        title: "کیفیت دوربین",
      },
      {
        content: " 8GB , 4GB",
        title: "هسته پردازنده",
      },
      {
        content: "32",
        title: "حافظه",
      },
    ],
    sells: 14,
    date: 26,
    rate: 5,
    reviews: 7,
    exist: false,
    amount: 1,
    core: [8, 4],
    hard: [32],
    camera: 13,
    ram: 2,
    networkType: 4,
  },
  {
    id: "5c4bc3.jpg",
    name: "گوشی موبایل شیائومی مدل 11T Pro 5G ظرفیت 256 گیگابایت و رم 12 گیگابایت",
    engName: "",
    model: "Xiaomi 11T Pro 5G 256/12 GB",
    categories: ["Mobile"],
    priceOn: 16_150_000,
    priceOff: null,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو عدد",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2021",
      },
      {
        content: "12GB",
        title: "رم",
      },
      {
        content: "108MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8GB",
        title: "هسته پردازنده",
      },
      {
        content: "256GB",
        title: "حافظه",
      },
    ],
    sells: 0,
    date: 14,
    rate: 0,
    reviews: 0,
    exist: false,
    amount: 1,
    core: [8],
    hard: [256],
    camera: 108,
    ram: 12,
    networkType: 5,
  },
  {
    id: "0371a6.jpg",
    name: "گوشی موبایل شیائومی مدل Poco X4 Pro 5G ظرفیت 256 گیگابایت - رم 8 گیگابایت",
    engName: "",
    model: "Xiaomi Poco X4 Pro 5G 256GB - 8GB RAM",
    categories: ["Mobile"],
    priceOn: 9_580_000,
    priceOff: 9_430_000,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو عدد",
      },
      {
        title: "توضیحات سیم کارت",
        content: " سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2022",
      },
      {
        content: "8GB",
        title: "رم",
      },
      {
        content: "108MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8GB, 4GB",
        title: "هسته پردازنده",
      },
      {
        content: "256GB",
        title: "حافظه",
      },
    ],
    sells: 0,
    date: 55,
    rate: 0,
    reviews: 0,
    exist: true,
    amount: 1,
    core: [8, 4],
    hard: [256],
    camera: 108,
    ram: 8,
    networkType: 4,
  },
  {
    id: "ca9a36.webp",
    name: "گوشی شیائومی Mi 10 5G / حافظه 256 رم 8 گیگابایت Xiaomi Mi 10 5G 8/256 GB",
    engName: "",
    model: "Xiaomi Mi 10 5G 8/256 GB",
    categories: ["Mobile"],
    priceOn: 12000000,
    priceOff: null,
    brand: "",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "1",
      },
      {
        title: "توضیحات سیم کارت",
        content: "6.67 اینچ",
      },
      {
        title: "سال تولید",
        content: "2023",
      },
      {
        content: "16GB",
        title: "رم",
      },
      {
        content: "136MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8GB, 4GB",
        title: "هسته پردازنده",
      },
      {
        content: "256GB",
        title: "حافظه",
      },
    ],
    sells: 632,
    date: 14,
    rate: 5,
    reviews: 316,
    exist: true,
    amount: 1,
    core: [8, 4],
    hard: [256],
    camera: 136,
    ram: 16,
    networkType: 5,
  },
  {
    id: "447a9f.jpg",
    name: "گوشی موبایل شیائومی Mi 11 Lite ظرفیت 128/8 گیگابایت",
    engName: "",
    model: "Xiaomi Mi 11 Lite",
    categories: ["Mobile"],
    priceOn: 7_770_000,
    priceOff: 7_658_000,
    brand: "samsung",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "1",
      },
      {
        title: "توضیحات سیم کارت",
        content: "میکرو",
      },
      {
        title: "سال تولید",
        content: "2019",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4GB",
        title: "هسته پردازنده",
      },
      {
        content: "128GB",
        title: "حافظه",
      },
    ],
    sells: 50,
    date: 142,
    rate: 4.5,
    reviews: 25,
    exist: true,
    amount: 1,
    core: [4],
    hard: [128],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "c07c0b.jpg",
    name: "گوشی موبایل شیائومی Mi 10T Pro 5G ظرفیت 256/8 گیگابایت",
    engName: "",
    model: "Xiaomi Mi 10T Pro 5G",
    categories: ["Mobile"],
    priceOn: 13_080_000,
    priceOff: 13_000_000,
    brand: "apple",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "1",
      },
      {
        title: "توضیحات سیم کارت",
        content: "نانو",
      },
      {
        title: "سال تولید",
        content: "2021",
      },
      {
        content: "8GB",
        title: "رم",
      },
      {
        content: "108GB",
        title: "کیفیت دوربین",
      },
      {
        content: "8GB, 4GB",
        title: "هسته پردازنده",
      },
      {
        content: "128GB",
        title: "حافظه",
      },
    ],
    sells: 0,
    date: 13,
    rate: 0,
    reviews: 0,
    exist: false,
    amount: 1,
    core: [8, 4],
    hard: [128],
    camera: 108,
    ram: 8,
    networkType: 5,
  },
  {
    id: "3cc018.jpg",
    name: "گوشی موبایل شیائومی Poco F3 5G ظرفیت 256/8 گیگابایت",
    engName: "",
    model: "Poco F3 5G",
    categories: ["Mobile"],
    priceOn: 10_900_000,
    priceOff: null,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "2",
      },
      {
        title: "توضیحات سیم کارت",
        content: "نانو و میکرو",
      },
      {
        title: "سال تولید",
        content: "2022",
      },
      {
        content: "8GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4GB",
        title: "هسته پردازنده",
      },
      {
        content: "128GB, 256GB",
        title: "حافظه",
      },
    ],
    sells: 122,
    date: 70,
    rate: 4.5,
    reviews: 60,
    exist: true,
    amount: 1,
    core: [4],
    hard: [128, 256],
    camera: 60,
    ram: 8,
    networkType: 5,
  },
  {
    id: "2de890.jpg",
    name: "گوشی موبایل شیائومی Mi 11 5G ظرفیت 256/8 گیگابایت",
    engName: "",
    model: "Mi 11 5G",
    categories: ["Mobile"],
    priceOn: 21_590_000,
    priceOff: null,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "دو سیمکارته",
      },
      {
        title: "توضیحات سیم کارت",
        content: "نانو",
      },
      {
        title: "سال تولید",
        content: "2023",
      },
      {
        content: "16GB",
        title: "رم",
      },
      {
        content: "108GB",
        title: "کیفیت دوربین",
      },
      {
        content: "16 , 8",
        title: "هسته پردازنده",
      },
      {
        content: "256GB",
        title: "حافظه",
      },
    ],
    sells: 506,
    date: 1,
    rate: 5,
    reviews: 255,
    exist: true,
    amount: 1,
    core: [16, 8],
    hard: [256],
    camera: 108,
    ram: 16,
    networkType: 5,
  },
  {
    id: "3cc0181.jpg",
    name: "گوشی موبایل شیائومی Poco F3 5G ظرفیت 128/6 گیگابایت",
    engName: "",
    model: "Poco F3 5G",
    categories: ["Mobile"],
    priceOn: 9_200_000,
    priceOff: 9_000_000,
    brand: "samsung",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "2",
      },
      {
        title: "توضیحات سیم کارت",
        content: "نانو",
      },
      {
        title: "سال تولید",
        content: "2021",
      },
      {
        content: "8GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8,16",
        title: "هسته پردازنده",
      },
      {
        content: "126GB",
        title: "حافظه",
      },
    ],
    sells: 700,
    date: 113,
    rate: 5,
    reviews: 350,
    exist: true,
    amount: 1,
    core: [8, 4],
    hard: [126],
    camera: 60,
    ram: 8,
    networkType: 4,
  },
  {
    id: "daa66f.jpg",
    name: "گوشی موبایل شیائومی Redmi Note 9 Pro Max ظرفیت 128/6 گیگابایت",
    engName: "",
    model: "Redmi Note 9 Pro Max",
    categories: ["Mobile"],
    priceOn: 7_030_000,
    priceOff: null,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "2",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "126MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4",
        title: "هسته پردازنده",
      },
      {
        content: "126GB",
        title: "حافظه",
      },
    ],
    sells: 100,
    date: 218,
    rate: 3,
    reviews: 50,
    exist: true,
    amount: 1,
    core: [4],
    hard: [126],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "c07c0b1.jpg",
    name: "گوشی موبایل شیائومی Mi 10T Pro 5G ظرفیت 128/8 گیگابایت",
    engName: "",
    model: "Xiaomi Mi 10T Pro 5G",
    categories: ["Mobile"],
    priceOn: 14_850_000,
    priceOff: 14_350_000,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "2",
      },
      {
        title: "توضیحات سیم کارت",
        content: "نانو",
      },
      {
        title: "سال تولید",
        content: "2022",
      },
      {
        content: "6GB",
        title: "رم",
      },
      {
        content: "108MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8",
        title: "هسته پردازنده",
      },
      {
        content: "256GB",
        title: "حافظه",
      },
    ],
    sells: 213,
    date: 43,
    rate: 4,
    reviews: 111,
    exist: true,
    amount: 1,
    core: [8],
    hard: [256],
    camera: 108,
    ram: 6,
    networkType: 4,
  },
  {
    id: "5692ed.jpg",
    name: "گوشی موبایل شیائومی Mi 10 Lite 5G ظرفیت 256/8 گیگابایت",
    engName: "",
    model: "Xiaomi Mi 10 Lite 5G",
    categories: ["Mobile"],
    priceOn: 11_490_000,
    priceOff: 11_000_000,
    brand: "",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "2",
      },
      {
        title: "توضیحات سیم کارت",
        content: "میکرو",
      },
      {
        title: "سال تولید",
        content: "2021",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8,4",
        title: "هسته پردازنده",
      },
      {
        content: "126GB",
        title: "حافظه",
      },
    ],
    sells: 950,
    date: 126,
    rate: 5,
    reviews: 430,
    exist: true,
    amount: 1,
    core: [8, 4],
    hard: [126],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "8effe1.jpg",
    name: "گوشی موبایل شیائومی Redmi 9C ظرفیت 64/3 گیگابایت",
    engName: "",
    model: "xiaomi redmi 9C",
    categories: ["Mobile"],
    priceOn: 4_620_000,
    priceOff: 4_500_000,
    brand: "samsung",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4",
        title: "هسته پردازنده",
      },
      {
        content: "126GB",
        title: "حافظه",
      },
    ],
    sells: 136,
    date: 12,
    rate: 5,
    reviews: 84,
    exist: true,
    amount: 1,
    core: [4],
    hard: [126],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "1fcac3.jpg",
    name: "گوشی موبایل شیائومی Mi 10 Lite 5G ظرفیت 128/6 گیگابایت",
    engName: "",
    model: "MI 10 LITE 5G",
    categories: ["Mobile"],
    priceOn: 12_940_000,
    priceOff: 12_000_000,
    brand: "samsung",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "8GB",
        title: "رم",
      },
      {
        content: "108MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8,4,2",
        title: "هسته پردازنده",
      },
      {
        content: "128GB, 256GB",
        title: "حافظه",
      },
    ],
    sells: 236,
    date: 3,
    rate: 4.2,
    reviews: 117,
    exist: true,
    amount: 1,
    core: [8, 4, 2],
    hard: [128, 256],
    camera: 108,
    ram: 8,
    networkType: 5,
  },
  {
    id: "416b33.jpg",
    name: "گوشی موبایل شیائومی Mi Note 10 Lite ظرفیت 64/6 گیگابایت",
    engName: "",
    model: "Mi Note 10 Lite",
    categories: ["Mobile"],
    priceOn: 7_030_000,
    priceOff: 7_000_000,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4,2",
        title: "هسته پردازنده",
      },
      {
        content: "128GB,64GB",
        title: "حافظه",
      },
    ],
    sells: 726,
    date: 45,
    rate: 3.2,
    reviews: 135,
    exist: true,
    amount: 1,
    core: [4, 2],
    hard: [128, 64],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "d65995.jpg",
    name: "گوشی موبایل شیائومی Redmi Note 8 Pro ظرفیت 64/6 گیگابایت",
    engName: "",
    model: "Xiaomi Redmi Note 9 Pro",
    categories: ["Mobile"],
    priceOn: 5_345_000,
    priceOff: null,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2019",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8,4,2",
        title: "هسته پردازنده",
      },
      {
        content: "128GB,64GB",
        title: "حافظه",
      },
    ],
    sells: 459,
    date: 129,
    rate: 5,
    reviews: 283,
    exist: true,
    amount: 1,
    core: [8, 4, 2],
    hard: [128, 64],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "ee271b.jpg",
    name: "گوشی موبایل شیائومی Redmi 7A ظرفیت 32/2 گیگابایت",
    engName: "",
    model: "Xiaomi Redmi 7a",
    categories: ["Mobile"],
    priceOn: 4_300_000,
    priceOff: 4_000_000,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: " دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2019",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4,2",
        title: "هسته پردازنده",
      },
      {
        content: "128GB, 64GB, 32GB",
        title: "حافظه",
      },
    ],
    sells: 794,
    date: 246,
    rate: 3.5,
    reviews: 300,
    exist: true,
    amount: 1,
    core: [4, 2],
    hard: [128, 64, 32],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "f80ada.jpg",
    name: " Redmi Note 9 ظرفیت 64/3 گیگابایت",
    engName: "",
    model: "Note 9",
    categories: ["Mobile"],
    priceOn: 4_350_000,
    priceOff: null,
    brand: "samsung",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "4,2",
        title: "هسته پردازنده",
      },
      {
        content: "64GB",
        title: "حافظه",
      },
    ],
    sells: 4,
    date: 95,
    rate: 2.5,
    reviews: 1,
    exist: true,
    amount: 1,
    core: [4, 2],
    hard: [64],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
  {
    id: "1a466a.jpg",
    name: "سامسونگ Redmi Note 9S ظرفیت 128/6 گیگابایت",
    engName: "",
    model: "Note 9s",
    categories: ["Mobile"],
    priceOn: 6_790_000,
    priceOff: 6_400_000,
    brand: "samsung",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "8GB",
        title: "رم",
      },
      {
        content: "108GB",
        title: "کیفیت دوربین",
      },
      {
        content: "8,4,2",
        title: "هسته پردازنده",
      },
      {
        content: "256GB, 128GB, 64GB",
        title: "حافظه",
      },
    ],
    sells: 550,
    date: 93,
    rate: 5,
    reviews: 320,
    exist: true,
    amount: 1,
    core: [8, 4, 2],
    hard: [256, 128, 64],
    camera: 108,
    ram: 8,
    networkType: 5,
  },
  {
    id: "0e6d94.jpg",
    name: "گوشی موبایل شیائومی Poco M3 ظرفیت 64/4 گیگابایت",
    engName: "",
    model: "Xiaomi Poco M3",
    categories: ["Mobile"],
    priceOn: 5_670_000,
    priceOff: 5_000_000,
    brand: "xi",
    features: [
      {
        title: "تعداد سیمکارت",
        content: "دو سیم کارت",
      },
      {
        title: "توضیحات سیم کارت",
        content: "سایز نانو (0.67 × 8.8 × 12.3 میلیمتر)",
      },
      {
        title: "سال تولید",
        content: "2020",
      },
      {
        content: "4GB",
        title: "رم",
      },
      {
        content: "60MPX",
        title: "کیفیت دوربین",
      },
      {
        content: "8,4,2",
        title: "هسته پردازنده",
      },
      {
        content: "128GB, 64GB, 32GB",
        title: "حافظه",
      },
    ],
    sells: 0,
    date: 0,
    rate: 0,
    reviews: 0,
    exist: false,
    amount: 1,
    core: [8, 6, 4],
    hard: [128, 64, 32],
    camera: 60,
    ram: 4,
    networkType: 4,
  },
];
